#include "stdafx.h"
#include "rgb_color_space_definition.h"

color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::sRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.64f, 0.33f, 0.3f, 0.6f, 0.15f, 0.06f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::adobeRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.64f, 0.33f, 0.21f, 0.71f, 0.15f, 0.06f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::pal_secam = color_space::rgb_color_space_definition::rgb_color_space_definition(0.64f, 0.33f, 0.29f, 0.6f, 0.15f, 0.06f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::americaNTSC = color_space::rgb_color_space_definition::rgb_color_space_definition(0.63f, 0.34f, 0.31f, 0.595f, 0.155f, 0.07f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::oldNTSC = color_space::rgb_color_space_definition::rgb_color_space_definition(0.67f, 0.33f, 0.21f, 0.71f, 0.14f, 0.08f, &color_space::white_point_presets::C_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::appleRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.625f, 0.34f, 0.28f, 0.595f, 0.155f, 0.07f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::dci_p3 = color_space::rgb_color_space_definition::rgb_color_space_definition(0.68f, 0.32f, 0.265f, 0.69f, 0.15f, 0.06f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::uhdtv = color_space::rgb_color_space_definition::rgb_color_space_definition(0.708f, 0.292f, 0.17f, 0.797f, 0.131f, 0.046f, &color_space::white_point_presets::D65_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::adobeWideGammutRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.735f, 0.265f, 0.115f, 0.826f, 0.157f, 0.018f, &color_space::white_point_presets::D50_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::rommRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.7347f, 0.2653f, 0.1596f, 0.8404f, 0.0366f, 0.0001f, &color_space::white_point_presets::D50_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::cieRGB = color_space::rgb_color_space_definition::rgb_color_space_definition(0.7347f, 0.2653f, 0.2738f, 0.7174f, 0.1666f, 0.0089f, &color_space::white_point_presets::E_2Degree);
color_space::rgb_color_space_definition color_space::rgb_color_space_definition_presets::cieXYZ = color_space::rgb_color_space_definition::rgb_color_space_definition(1.f, 0.f, 0.f, 1.f, 0.f, 0.f, &color_space::white_point_presets::E_2Degree);